/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mrm21632.chatapi;

import com.mrm21632.chatapi.controllers.ServerController;

import static spark.Spark.port;

public class Application {
    public static void main(String[] args) {
        port(8080);
        ServerController.run();
    }
}
